"""Populate the stations table. Idempotent — safe to re-run.

    python scripts/seed_stations.py

Two sources, both asserted against each other:

  live CPCB API      -> station_name, city, latitude, longitude
  docs/station_mapping.md -> openaq_location_id

The mapping doc is GENERATED by scripts/probe_history.py. A generated file
drifting out of sync with the live station list is precisely the silent
row-dropping failure Gate 0.2 exists to catch, so this script refuses to seed
unless both sides agree exactly. If it fails, re-run:

    python scripts/probe_history.py --write-doc
"""

import os
import re
import sys

from cpcb_api import FetchError, fetch, load_key, parse_value
from db import connect

MAPPING_DOC = os.path.join(os.path.dirname(__file__), "..", "docs", "station_mapping.md")

# Matches a row of the "Historical depth" table:
#   | `Amity University, Panchgaon - IITM` | 3410004 | exact | ... |
#
# The station name is captured from INSIDE the backticks with [^`]+, which
# preserves the trailing space in 'Sector-6, Panchkula - HSPCB ' and the double
# space in 'Municipal Corporation Office, Dharuhera -  HSPCB'. Those must
# survive byte-for-byte — see the comment on stations.station_name.
#
# [^`]+ rather than .+? also makes the earlier "Manual mapping rows" table
# unmatchable (its second column is a backticked string, not a number), so the
# two tables cannot be confused for one another.
DEPTH_ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*(\d+)\s*\|")


def parse_mapping_doc() -> dict[str, int]:
    if not os.path.exists(MAPPING_DOC):
        sys.exit(
            f"{os.path.normpath(MAPPING_DOC)} not found. "
            "Run: python scripts/probe_history.py --write-doc"
        )

    mapping: dict[str, int] = {}
    with open(MAPPING_DOC, encoding="utf-8") as fh:
        for line in fh:
            m = DEPTH_ROW.match(line.rstrip("\n"))
            if m:
                name, openaq_id = m.group(1), int(m.group(2))
                if name in mapping and mapping[name] != openaq_id:
                    sys.exit(f"mapping doc gives two OpenAQ ids for {name!r}")
                mapping[name] = openaq_id

    if not mapping:
        sys.exit(
            f"parsed 0 rows from {os.path.normpath(MAPPING_DOC)}. "
            "The generated table format changed — fix this regex, do not hand-edit the doc."
        )
    return mapping


def main() -> int:
    try:
        records = fetch("Haryana", load_key())
    except FetchError as e:
        sys.exit(str(e))

    # One entry per station; every pollutant row repeats the same station metadata.
    live: dict[str, dict] = {}
    for r in records:
        live.setdefault(r["station"], r)

    mapping = parse_mapping_doc()

    # The accounting assertion, same shape as Gate 0.2. A station present on one
    # side and absent on the other is never ignored.
    only_live = sorted(set(live) - set(mapping))
    only_doc = sorted(set(mapping) - set(live))
    if only_live or only_doc:
        for name in only_live:
            print(f"  LIVE BUT UNMAPPED  {name!r}", file=sys.stderr)
        for name in only_doc:
            print(f"  MAPPED BUT NOT LIVE {name!r}", file=sys.stderr)
        sys.exit(
            f"station list and mapping doc disagree "
            f"({len(only_live)} live-only, {len(only_doc)} doc-only). "
            "CPCB changed its station list. Re-run: python scripts/probe_history.py --write-doc"
        )

    rows = [
        (
            name,
            r["city"],
            parse_value(r["latitude"]),
            parse_value(r["longitude"]),
            mapping[name],
        )
        for name, r in sorted(live.items())
    ]

    with connect() as conn:
        with conn.cursor() as cur:
            # station_id is deliberately NOT touched on conflict: observations
            # reference it, so it must stay stable across re-seeds.
            cur.executemany(
                """
                INSERT INTO stations
                    (station_name, city, latitude, longitude, openaq_location_id)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (station_name) DO UPDATE SET
                    city               = EXCLUDED.city,
                    latitude           = EXCLUDED.latitude,
                    longitude          = EXCLUDED.longitude,
                    openaq_location_id = EXCLUDED.openaq_location_id
                """,
                rows,
            )
        conn.commit()

        with conn.cursor() as cur:
            cur.execute(
                "SELECT count(*), count(openaq_location_id) FROM stations WHERE is_active"
            )
            total, with_openaq = cur.fetchone()

    print(f"seeded {len(rows)} stations from the live API")
    print(f"stations table: {total} active, {with_openaq} with an OpenAQ id")

    if total != with_openaq:
        sys.exit(f"{total - with_openaq} station(s) have no OpenAQ id — Phase 3 needs all of them")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
